#from .ClienteViejo import Clientes as clientesViejoResource
#from .ClienteViejo import Cliente as clienteViejoResource
from .Cliente import Clientes as ClientesResource
from .Cliente import Cliente as ClienteResource
from .Comida import Comidas as ComidasResource
from .Comida import Comida as ComidaResource
from .Pedido import Pedidos as PedidosResource
from .Pedido import Pedido as PedidoResource
from .Restaurante import Restaurantes as RestaurantesResource
from .Restaurante import Restaurante as RestauranteResource
